spring:
  security:
    user:
      name: soknem
      password: 1234
  application:
    name: spring_bank_api
#  profiles:
#    active:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    username: postgres
    password: 14022002
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/mobile_banking_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /
fileStorage:
  image_location: "fileStorage/images/"
  image_client: "images/**"
